exclude: "(alembic|core/[a-z_]*.py|core/scripts/[a-z_]*.py)"

repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: ^test_redis/
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
            "--ignore-init-module-imports",
            "--recursive",
          ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^test_redis/

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=100
          - --target-version=py38

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^test_redis/
        additional_dependencies:
          - flake8-bugbear
          - flake8-bandit
          - flake8-blind-except
          - flake8-docstrings
          - flake8-logging-format
          - flake8-print

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
      - id: pyupgrade
        exclude: ^test_redis/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        exclude: ^test_redis/
        additional_dependencies:
          - pydantic
          - types-geoip2
          - sqlalchemy-stubs
          - types-pytz
          - types-redis
          - types-PyYAML

  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v14.0.6
  #   hooks:
  #     - id: clang-format
  #       "types_or": [c++, c, cuda]

  # TODO: Add pylint
  # - repo: https://github.com/pycqa/pylint
  #   rev: v2.14.3
  #   hooks:
  #     - id: pylint
  #       exclude: ^test_redis/
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [python]
  #       args: [
  #           "-rn", # Only display messages
  #           "-sn", # Don't display the score
  #         ]
