version: '3.9'

services:
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak:16.1.1
    command:
      - "-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - app-keycloak-data:/opt/jboss/keycloak/standalone/data/
      - ./realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    restart: unless-stopped

volumes:
  app-postgres-data:
  app-keycloak-data:
